# Generated by Django 5.0.4 on 2026-04-11 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('location', models.CharField(max_length=200, verbose_name='Ort')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tage',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Startdatum')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Enddatum')),
                ('base_currency', models.CharField(default='EUR', max_length=10, verbose_name='Basis-Währung')),
                ('local_currency', models.CharField(default='THB', max_length=10, verbose_name='Lokal-Währung')),
            ],
            options={
                'verbose_name': 'Reise',
                'verbose_name_plural': 'Reisen',
            },
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Tagebuch Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diary', to='travel.day')),
            ],
            options={
                'verbose_name': 'Tagebucheintrag',
                'verbose_name_plural': 'Tagebucheinträge',
            },
        ),
        migrations.CreateModel(
            name='DiaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diary/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travel.diaryentry')),
            ],
            options={
                'verbose_name': 'Tagebuch Bild',
                'verbose_name_plural': 'Tagebuch Bilder',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('type', models.CharField(choices=[('FLIGHT', 'Flug'), ('HOTEL', 'Unterkunft'), ('ACTIVITY', 'Aktivität'), ('TRANSPORT', 'Transport'), ('OTHER', 'Sonstiges')], default='ACTIVITY', max_length=20, verbose_name='Typ')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Uhrzeit')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Endzeit')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('booking_reference', models.CharField(blank=True, max_length=100, verbose_name='Buchungsnummer')),
                ('voucher', models.FileField(blank=True, null=True, upload_to='vouchers/', verbose_name='Voucher/Anhang')),
                ('cost_local', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kosten lokal')),
                ('cost_base', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kosten Basis (EUR)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Bezahlt')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='travel.day')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['time', 'id'],
            },
        ),
        migrations.AddField(
            model_name='day',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='travel.trip'),
        ),
    ]
