# Generated by Django 5.0.4 on 2026-04-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booking_via',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gebucht über'),
        ),
        migrations.AddField(
            model_name='event',
            name='detail_info',
            field=models.CharField(blank=True, max_length=255, verbose_name='Details (Flug-Nr, Terminal, etc.)'),
        ),
    ]
