# Generated by Django 5.0.4 on 2026-04-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_event_booking_via_event_detail_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booking_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Buchungs-Link'),
        ),
    ]
