# Generated by Django 5.0.4 on 2026-04-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_event_booking_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='activities_info',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ausflüge und Eintritt'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kosten tatsächlich'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_booked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preis gebucht'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_estimated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kosten geschätzt'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_per_person',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pro Nase'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Summe'),
        ),
        migrations.AddField(
            model_name='event',
            name='meals_info',
            field=models.CharField(blank=True, max_length=255, verbose_name='Essen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cost_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kosten Basis EUR (legacy)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cost_local',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kosten lokal (legacy)'),
        ),
    ]
