# Generated by Django 5.0.4 on 2026-04-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_event_activities_info_event_cost_actual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='persons_count',
            field=models.PositiveIntegerField(default=2, verbose_name='Anzahl Personen'),
        ),
    ]
