# Generated by Django 5.0.4 on 2026-04-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_trip_persons_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='distance_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Entfernung (km)'),
        ),
    ]
