# Generated by Django 5.0.4 on 2026-04-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_event_distance_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('FLIGHT', '✈️ Flugzeug'), ('HOTEL', '🏨 Hotel'), ('CAMPING', '⛺ Campingplatz'), ('PITCH', '🚐📍 Womo-Stellplatz'), ('BUNGALOW', '🏡 Bungalow'), ('CAMPER', '🚐 Womo (Fahrt)'), ('CAR', '🚗 Auto'), ('BOAT', '🛥️ Boot'), ('TAXI', '🚕 Taxi'), ('BUS', '🚌 Bus'), ('TRAIN', '🚆 Zug'), ('ACTIVITY', '🎒 Aktivität'), ('RESTAURANT', '🍽️ Restaurant'), ('OTHER', '❓ Sonstiges')], default='ACTIVITY', max_length=20, verbose_name='Typ'),
        ),
    ]
