# Generated by Django 5.0.4 on 2026-04-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_alter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ort / Ziel'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('NONE', '---'), ('FLIGHT', '✈️ Flug'), ('HOTEL', '🏨 Hotel'), ('CAMPING', '⛺ Camping'), ('PITCH', '🚐📍 Stellplatz'), ('BUNGALOW', '🏡 Bungalow'), ('CAMPER', '🚐 Wohnmobil'), ('CAR', '🚗 Auto'), ('BOAT', '🛥️ Boot'), ('TAXI', '🚕 Taxi'), ('BUS', '🚌 Bus'), ('TRAIN', '🚆 Zug'), ('ACTIVITY', '🎒 Aktivität'), ('RESTAURANT', '🍽️ Essen'), ('OTHER', '❓ Sonstiges')], default='NONE', max_length=20, verbose_name='Typ'),
        ),
    ]
