# Generated by Django 5.0.4 on 2026-04-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_event_location_alter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bereits gezahlt'),
        ),
        migrations.AddField(
            model_name='event',
            name='cancellation_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Kostenlos stornierbar bis'),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_method',
            field=models.CharField(choices=[('NONE', '---'), ('CC', 'Kreditkarte'), ('PAYPAL', 'PayPal'), ('CASH', 'Bar'), ('TRANSFER', 'Überweisung'), ('EC', 'EC-Karte')], default='NONE', max_length=20, verbose_name='Zahlungsmethode'),
        ),
    ]
