# Generated by Django 5.0.4 on 2026-04-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_event_amount_paid_event_cancellation_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Globale Einstellung',
                'verbose_name_plural': 'Globale Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='TripTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name der Vorlage')),
                ('preferences', models.TextField(help_text='Beschreibe hier deine Standard-Wünsche für diese Art von Reise.', verbose_name='Reise-Präferenzen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reise-Vorlage',
                'verbose_name_plural': 'Reise-Vorlagen',
            },
        ),
    ]
