# Generated by Django 5.0.4 on 2026-04-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_globalsetting_triptemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='persons_ages',
            field=models.CharField(blank=True, help_text="Komma-separiert, z.B. '40, 38, 12'", max_length=100, verbose_name='Alter der Personen'),
        ),
    ]
