# Generated by Django 5.0.4 on 2026-04-13 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_trip_persons_ages'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='linked_checkout',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_checkin', to='travel.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='nights',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nächte'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('NONE', '---'), ('FLIGHT', '✈️ Flug'), ('HOTEL', '🏨 Hotel'), ('CAMPING', '⛺ Camping'), ('PITCH', '🚐📍 Stellplatz'), ('BUNGALOW', '🏡 Bungalow'), ('CAMPER', '🚐 Wohnmobil'), ('CAR', '🚗 Auto'), ('SCOOTER', '🛵 Roller'), ('BOAT', '🛥️ Boot'), ('FERRY', '⛴️ Fähre'), ('TAXI', '🚕 Taxi'), ('BUS', '🚌 Bus'), ('TRAIN', '🚆 Zug'), ('ACTIVITY', '🎒 Aktivität'), ('RESTAURANT', '🍽️ Essen'), ('OTHER', '❓ Sonstiges')], default='NONE', max_length=20, verbose_name='Typ'),
        ),
    ]
