# Generated by Django 5.0.4 on 2026-04-14 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_event_linked_checkout_event_nights_alter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='breakfast_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Frühstück Preis'),
        ),
        migrations.AddField(
            model_name='event',
            name='breakfast_included',
            field=models.BooleanField(default=False, verbose_name='Frühstück inkl.'),
        ),
        migrations.CreateModel(
            name='GlobalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('expense_type', models.CharField(choices=[('FOOD', '🍟 Verpflegung'), ('RENTAL', '🛴 Miete (Roller/Surf/etc)'), ('FEE', '🎟️ Eintritt/Gebühr'), ('OTHER', '📦 Sonstiges')], default='OTHER', max_length=20, verbose_name='Typ')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preis pro Einheit')),
                ('units', models.PositiveIntegerField(default=1, verbose_name='Anzahl Einheiten')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gesamtbetrag')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_auto_calculated', models.BooleanField(default=False, verbose_name='Automatisch berechnet')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_expenses', to='travel.trip')),
            ],
            options={
                'verbose_name': 'Globale Ausgabe',
                'verbose_name_plural': 'Globale Ausgaben',
                'ordering': ['expense_type', 'id'],
            },
        ),
    ]
