# Generated by Django 5.0.4 on 2026-04-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_event_breakfast_cost_event_breakfast_included_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalexpense',
            name='voucher',
            field=models.FileField(blank=True, null=True, upload_to='vouchers/', verbose_name='Voucher/Anhang'),
        ),
    ]
