# Generated by Django 5.0.4 on 2026-04-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_globalexpense_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('NONE', '---'), ('FLIGHT', '✈️ Flug'), ('HOTEL', '🏨 Hotel'), ('CAMPING', '⛺ Camping'), ('PITCH', '🚐📍 Stellplatz'), ('BUNGALOW', '🏡 Bungalow'), ('CAMPER', '🚐 Wohnmobil'), ('CAR', '🚗 Auto'), ('SCOOTER', '🛵 Roller'), ('BOAT', '🛥️ Boot'), ('FERRY', '⛴️ Fähre'), ('TAXI', '🚕 Taxi'), ('BUS', '🚌 Bus'), ('TRAIN', '🚆 Zug'), ('RENTAL_CAR', '🔑🚗 Mietwagen'), ('ACTIVITY', '🎒 Aktivität'), ('RESTAURANT', '🍽️ Essen'), ('OTHER', '❓ Sonstiges')], default='NONE', max_length=20, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='globalexpense',
            name='expense_type',
            field=models.CharField(choices=[('FOOD', '🍟 Verpflegung'), ('RENTAL', '🛴 Miete (Roller/Surf/etc)'), ('RENTAL_CAR', '🔑🚗 Mietwagen'), ('FEE', '🎟️ Eintritt/Gebühr'), ('OTHER', '📦 Sonstiges')], default='OTHER', max_length=20, verbose_name='Typ'),
        ),
    ]
