# Generated by Django 5.0.4 on 2026-04-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_alter_event_type_alter_globalexpense_expense_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['time', 'id'], 'verbose_name': 'Eintrag', 'verbose_name_plural': 'Einträge'},
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('NONE', '---'), ('FLIGHT', '✈️ Flug'), ('HOTEL', '🏨 Hotel'), ('CAMPING', '⛺ Campingplatz'), ('PITCH', '🚐📍 Stellplatz'), ('BUNGALOW', '🏡 Bungalow'), ('CAMPER', '🚐 Wohnmobil'), ('CAR', '🚗 Auto'), ('SCOOTER', '🛵 Roller'), ('BOAT', '🛥️ Boot'), ('FERRY', '⛴️ Fähre'), ('TAXI', '🚕 Taxi'), ('BUS', '🚌 Bus'), ('TRAIN', '🚆 Zug / Bahn'), ('METRO', '🚇 Metro / U-Bahn'), ('TRAM', '🚋 Straßenbahn / Tram'), ('RENTAL_CAR', '🔑🚗 Mietwagen'), ('ACTIVITY', '🎒 Aktivität'), ('RESTAURANT', '🍽️ Essen'), ('OTHER', '❓ Sonstiges')], default='NONE', max_length=20, verbose_name='Typ'),
        ),
    ]
