# Generated by Django 5.0.4 on 2026-04-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0016_alter_event_options_alter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
