# Generated by Django 5.0.4 on 2026-04-15 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0017_diaryimage_is_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategorie')),
                ('icon', models.CharField(default='bi-list-check', max_length=50, verbose_name='Icon (Bootstrap)')),
                ('order', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Checklisten-Kategorie',
                'verbose_name_plural': 'Checklisten-Kategorien',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Vorlagen-Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
            ],
            options={
                'verbose_name': 'Checklisten-Vorlage',
                'verbose_name_plural': 'Checklisten-Vorlagen',
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Eintrag')),
                ('due_days_before', models.IntegerField(default=0, verbose_name='Tage vor Abreise')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.checklistcategory')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='travel.checklisttemplate')),
            ],
            options={
                'verbose_name': 'Checklisten-Eintrag (Vorlage)',
                'verbose_name_plural': 'Checklisten-Einträge (Vorlage)',
            },
        ),
        migrations.CreateModel(
            name='TripChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.checklisttemplate')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='travel.trip')),
            ],
            options={
                'verbose_name': 'Reise-Checkliste',
                'verbose_name_plural': 'Reise-Checklisten',
            },
        ),
        migrations.CreateModel(
            name='TripChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Eintrag')),
                ('is_checked', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fällig am')),
                ('is_template_item', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel.checklistcategory')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='travel.tripchecklist')),
            ],
            options={
                'verbose_name': 'Reise-Checklisten-Eintrag',
                'verbose_name_plural': 'Reise-Checklisten-Einträge',
                'ordering': ['is_checked', 'category', 'id'],
            },
        ),
    ]
