# Generated by Django 5.0.4 on 2026-04-15 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0018_checklistcategory_checklisttemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='ui_settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='UI Einstellungen'),
        ),
        migrations.AlterField(
            model_name='checklistitemtemplate',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_items', to='travel.checklistcategory'),
        ),
        migrations.AlterField(
            model_name='tripchecklistitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_items', to='travel.checklistcategory'),
        ),
    ]
