# Generated by Django 5.0.4 on 2026-04-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0019_trip_ui_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='breakfast_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Frühstück Preis'),
        ),
    ]
