# Generated by Django 5.0.4 on 2026-04-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0020_alter_event_breakfast_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breitengrad'),
        ),
        migrations.AddField(
            model_name='day',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Längengrad'),
        ),
    ]
