# Generated by Django 5.0.4 on 2026-04-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0021_day_latitude_day_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='is_geocoded',
            field=models.BooleanField(default=False, verbose_name='Geokodierung versucht'),
        ),
    ]
