# Generated by Django 5.0.4 on 2026-04-18 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0022_day_is_geocoded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='globalexpense',
            name='voucher',
        ),
        migrations.CreateModel(
            name='TripVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vouchers/', verbose_name='Beleg')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Original-Dateiname')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='travel.event')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='travel.globalexpense')),
            ],
            options={
                'verbose_name': 'Beleg / Anhang',
                'verbose_name_plural': 'Belege / Anhänge',
            },
        ),
    ]
