# Generated by Django 5.0.4 on 2026-04-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0023_remove_event_voucher_remove_globalexpense_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_geocoded',
            field=models.BooleanField(default=False, verbose_name='Geokodiert'),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breitengrad'),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Längengrad'),
        ),
    ]
