# Generated by Django 5.0.4 on 2026-04-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0024_event_is_geocoded_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='station',
            field=models.CharField(blank=True, help_text="Gruppierungs-Name (z.B. 'Anreise' oder 'Palawan')", max_length=200, verbose_name='Station'),
        ),
    ]
