# Generated by Django 5.0.4 on 2026-04-20 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0027_assign_existing_trips'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalsetting',
            options={'verbose_name': 'Einstellung', 'verbose_name_plural': 'Einstellungen'},
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='triptemplate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='globalsetting',
            unique_together={('user', 'key')},
        ),
    ]
