# Generated by Django 5.0.4 on 2026-04-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0029_assign_templates_and_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='polarsteps_step_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Polarsteps Step ID'),
        ),
        migrations.AddField(
            model_name='trip',
            name='polarsteps_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Polarsteps Trip ID'),
        ),
    ]
