# Generated by Django 5.0.4 on 2026-04-20 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0030_diaryentry_polarsteps_step_id_trip_polarsteps_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='polarsteps_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Polarsteps Trip ID'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(condition=models.Q(('polarsteps_id__isnull', False)), fields=('user', 'polarsteps_id'), name='unique_user_polarsteps_trip'),
        ),
    ]
