# Generated by Django 5.0.4 on 2026-04-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0031_alter_trip_polarsteps_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryimage',
            name='remote_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Remote Photo URL'),
        ),
        migrations.AddField(
            model_name='trip',
            name='polarsteps_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Polarsteps URL'),
        ),
        migrations.AlterField(
            model_name='diaryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diary/'),
        ),
    ]
