# Generated by Django 5.0.4 on 2026-04-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0032_diaryimage_remote_url_trip_polarsteps_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='polarsteps_step_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
