# Generated by Django 5.0.4 on 2026-04-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0033_event_polarsteps_step_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='departure_is_geocoded',
            field=models.BooleanField(default=False, verbose_name='Start-Geokodierung versucht'),
        ),
        migrations.AddField(
            model_name='day',
            name='departure_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Start-Breitengrad'),
        ),
        migrations.AddField(
            model_name='day',
            name='departure_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Start-Längengrad'),
        ),
    ]
