# Generated by Django 5.0.4 on 2026-05-11 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0034_day_departure_is_geocoded_day_departure_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Breitengrad')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Längengrad')),
                ('alt', models.IntegerField(blank=True, null=True, verbose_name='Höhe')),
                ('speed', models.IntegerField(blank=True, null=True, verbose_name='Geschwindigkeit (km/h)')),
                ('timestamp_utc', models.DateTimeField(verbose_name='Zeitstempel (UTC)')),
                ('timestamp_local', models.DateTimeField(blank=True, null=True, verbose_name='Zeitstempel (Lokal)')),
                ('status', models.CharField(choices=[('RAW', 'Rohdaten'), ('PROCESSED', 'Verarbeitet'), ('IMPORTED', 'Übernommen'), ('ARCHIVED', 'Archiviert')], default='RAW', max_length=20, verbose_name='Status')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Rohdaten')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_points', to='travel.day')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_points', to='travel.trip')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tracking Punkt',
                'verbose_name_plural': 'Tracking Punkte',
                'ordering': ['-timestamp_utc'],
            },
        ),
    ]
