# Generated by Django 5.0.4 on 2026-05-11 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0035_trackingpoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Vorschlag')),
                ('suggestion_type', models.CharField(max_length=50, verbose_name='Typ')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Startzeit')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Endzeit')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breitengrad')),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Längengrad')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen/Info')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Bearbeitet')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Übernommen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_suggestions', to='travel.day')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_suggestions', to='travel.trip')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tracking Vorschlag',
                'verbose_name_plural': 'Tracking Vorschläge',
                'ordering': ['start_time'],
            },
        ),
    ]
