# Generated by Django 5.0.4 on 2026-05-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0036_trackingsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingpoint',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Zeitzone'),
        ),
    ]
