# Generated by Django 5.0.4 on 2026-05-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0037_trackingpoint_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingsuggestion',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Entfernung (km)'),
        ),
    ]
